# -*- coding: utf-8 -*-
"""3.1 Modelos ARIMA F

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_XDc9OOqMuKFG8Mdo74sRIbC2Ydpowj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.arima.model import ARIMA
from google.colab import files

# Step 1: Upload Excel file for a single company
print("Upload stock data Excel file (e.g., AAPL.xlsx)")
uploaded = files.upload()
stock_file = list(uploaded.keys())[0]
stock_data = pd.read_excel(stock_file)

# Step 2: Extract Closing price column and set Date index
if 'Date' in stock_data.columns:
    stock_data['Date'] = pd.to_datetime(stock_data['Date'])
    stock_data = stock_data.set_index('Date')
    stock_close = stock_data['Close'].dropna()
else:
    stock_close = stock_data['Close'].dropna()
    print("Warning: No Date column found, assuming sequential data")

print(f"Length of stock closing prices: {len(stock_close)}")

# Step 3: Random Walk Simulation
np.random.seed(42)
random_walk = np.cumsum(np.random.normal(0, 1, len(stock_close)))
random_walk = random_walk + stock_close.iloc[0]  # Start at same initial price
random_walk_series = pd.Series(random_walk, index=stock_close.index)

# Step 4: Perform Augmented Dickey-Fuller (ADF) Unit Root Test
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nADF Unit Root Test for {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    if result[1] < 0.05:
        print(f'{name} is stationary (reject null hypothesis of unit root)')
    else:
        print(f'{name} is non-stationary (fail to reject null hypothesis of unit root)')

# Run ADF test on original series and random walk
adf_test(stock_close, 'Stock Closing Prices')
adf_test(random_walk_series, 'Random Walk Simulation')

# If non-stationary, take first differences
stock_diff = stock_close.diff().dropna()
adf_test(stock_diff, 'Differenced Stock Closing Prices')

# Step 5: Perform Cointegration Test between Stock and Random Walk
print("\nCointegration Test between Stock Closing Prices and Random Walk:")
try:
    score, p_value, _ = coint(stock_close, random_walk_series)
    print(f'Cointegration Test Statistic: {score:.4f}')
    print(f'p-value: {p_value:.4f}')
    if p_value < 0.05:
        print("Stock and Random Walk are cointegrated (reject null hypothesis)")
    else:
        print("Stock and Random Walk are not cointegrated (fail to reject null hypothesis)")
except ValueError as e:
    print(f"Error in cointegration test: {e}")

# Step 6: Fit ARIMA Model
def fit_arima(series, name, order=(1,1,1)):
    model = ARIMA(series, order=order)
    results = model.fit()
    print(f'\nARIMA Model Summary for {name}:')
    print(results.summary())
    return results

# Fit ARIMA model
arima_model = fit_arima(stock_close, 'Stock Closing Prices', order=(1,1,1))

# Plot residuals
plt.figure(figsize=(10,4))
plt.plot(arima_model.resid)
plt.title('ARIMA Residuals for Stock')
plt.tight_layout()
plt.show()

# Step 7: Plot Closing Prices and Random Walk
plt.figure(figsize=(10,6))
plt.plot(stock_close, label='Stock Close')
plt.plot(random_walk_series, label='Random Walk', linestyle='--')
plt.title('Stock Closing Prices vs Random Walk')
plt.legend()
plt.show()